### ISSUE TITLE
Config.yaml format

### ISSUE THREAD

**Issue by HiroSato1** [Henningson/SSSLsquared#1]
Hello, 

I am a graduate student, in computer science in the U.S, who is interested in this work, and wanted to see if I can repricate the results, but it seems that the config.yaml file is needed for the training but I can't seem to find it anywhere on the repository. 

If I can see an example of the config file that would be great. if not, what would the feature in the config mean? 

I have the HLE dataset already cloned so I just want to get help for figuring out few things. 

Thank you so much!

Hiro

**Comment by Henningson** [comment]
Hey Hiro, 

sorry for the late response! I somehow totally missed this.
And thanks for telling me this, you seem to be the first person who actually tested this, lol.

Were you able to get it running yet?
I'm on vacation for the next two weeks, but after that  I can help you with setting everything up.
If I remember correctly, feature does mean how many DoubleConvs you use, and the number of channels, so you would need to supply something like [32,64,128,...]

You can also hit me up via E-Mail: jann-ole.henningson@fau.de

Best regards
Jann-Ole

**Comment by HiroSato1** [comment]
Hello, Dr. Jann, 

Thank you so much for your response! 

I was able to get it running somehow by stitching together the configuration from different .py files, but because I had some random configuration, the model performance was not good.  I only managed to run train.py, and I still haven't run the train_sharan.py, train_reg.py, and channel_wise; so when you are back and if you could help me set everything up, that would be fantastic!

Thank you so much for the email address! I will reach out to you via email after I try different configurations and will keep you updated!

Thank you so much!
Hiro

**Comment by Henningson** [comment]
Hey Hiro,

I just had a quick look at the code.
I really got to clean up here, sorry for that.
But good that you got something running for now.

To train the general U-Net, use the train_reg.py without any regularizers and with SGD instead of Adam.
I can't really tell you the exact features I used, for this I need to access my work pc.
But, when I'm back I'll upload the config files I used to train everything.

But please feel free to play around, maybe you find some configuration that makes it even better!
Or, you find a way to make Sharan's method work. I'd be delighted if that happened.

Best regards
Jann-Ole

**Comment by Henningson** [comment]
Heyhey, 

I just had a quick look, and added the missing config files to the main-branch.

Furthermore, I refactored some stuff and added more information to the README that should make set up easier.
I also renamed the train_reg.py to train.py and removed the old train.py altogether, as I used that file to train everything.

You should be able to run the minimal example in the readme file for training, as well as get the supplied U-Net models to run with the inference.py now.

If you have any more question, just shoot me a message, I am happy to help. :)

Edit: Ah almost forgot. Remember to checkout the new main branch

**Comment by HiroSato1** [comment]
Hello,  Dr. Jann,

My apologies for a late response, it has been busy few weeks for me.

I will definitely check them out and if I come up with any questions, I will send you a message :) 

Thank you so much for your help!!

Hiro
